### PR TITLE
fix missing 'end' and 'start' in context for custom graphite template…

### PR DESCRIPTION
**Pull request by ornoone**
this PR allow to write a custom template graph which change by selecting a time range in the graph page.

I am using linux-snmp to get my metrics, and it seem that some custom graphs don't change by selecting a time range in the webui. 

neither 1 day, 1 week or others change the graph. it seem the template I have in /var/lib/shinken/share/templates/graphite don't include the `from=` or `until=` required by graphite. but it seem that these values are not available in the template since only host, service and uri is inserted in the context.

I just added end and start to this template and it seem to work with a modified templates in /var/lib/shinken/share/templates/graphite (added `&from=${start}&until=${end}` at the end of each templates)

### CODE REVIEW

**Comment by maethor** [comment]
Thank you very much @ornoone ! I'm not using graphite myself so I cannot test your PR. Can I trust you and merge + deploy it?

I will take a look at the code to see if nothing seems crazy.

**Comment by ornoone** [comment]
I fixed a misscopy, but I now use this version in my shinken and the graph work well, and my dates ranges are respected.

**Comment by ornoone** [comment]
after some usage and a rollback, i can confirm that this fix is mandatory to allow tab in «graph» to work properly.
in the worst case, it's useless to add these values in the formater, and they will not be used...

**Comment by mohierf** [comment]
I tested and it is ok for me. I will merge this

**Pull request closed without merging**
